### ISSUE TITLE
Signs at NE direction is not visible significantly

### ISSUE THREAD

**Issue by telk5093** [kiwitreekor/korean_station#22]
![image](https://user-images.githubusercontent.com/10726524/85311871-09a2be80-b4f1-11ea-8c9a-c8b5c70e1485.png)

Signs at NE direction(↗) is not visible well if there is (very) many wating passengers.
I can't recognize that signs are exists because of peep's graphic.
I have no idea wether it IS exists but hidden by peeps, or invisible since it is a bug.

대기 승객량이 많으면 북동 방향(↗) 역명판이 잘 보이지 않습니다.
사람 그래픽때문에 역명판이 제대로 보이지 않습니다.
실제로 있는데 안 보이는 건지, 버그로 인해 안 보이게 된 것인지는 모르겠습니다.

**Comment by kiwitreekor** [comment]
![image](https://user-images.githubusercontent.com/24273113/85502429-40c4bd00-b622-11ea-9a89-fd7f8df0c0f9.png)
실제로 있는데 안 보이는 것 같습니다.

**Comment by kiwitreekor** [comment]
69bb3b3 에서 Sign A의 레이아웃을 변경함으로써 해결됨
