### ISSUE TITLE
서울역 건물에 승객 스프라이트가 겹침

### ISSUE THREAD

**Issue by JukjeonWani** [kiwitreekor/korean_station#27]
![화면 캡처 2021-09-17 225351](https://user-images.githubusercontent.com/88026704/133794566-abde25d0-0412-43ed-b544-5d768d05cede.jpg)
![화면 캡처 2021-09-17 225403](https://user-images.githubusercontent.com/88026704/133794572-56e6692f-4fbf-4692-81e5-ef95a963f5bf.jpg)

**Comment by kiwitreekor** [comment]
Fixed via 295fcaa
