### ISSUE TITLE
[Bug] 건설 창 스프라이트 오류

### ISSUE THREAD

**Issue by JukjeonWani** [kiwitreekor/korean_station#35]
![image](https://user-images.githubusercontent.com/88026704/215267691-2e80eaa2-f3b0-4fae-b076-0c5ec20794cf.png)
세로방향 선상역사 미리보기 타일이 잘못됨

**Comment by kiwitreekor** [comment]
OpenTTD 정식 버전 20230127일자 빌드, JGRPP 0.50.1까지 정상 작동하고, JGRPP 0.50.2에서만 해당 현상이 재현됩니다. JGRPP 쪽으로 문의해 주세요.
