### ISSUE TITLE
Add High+Low Platform C

### ISSUE THREAD

**Issue by Star7634** [kiwitreekor/korean_station#8]
성환역과 평택역처럼 C형 승강장을 한 쪽 승강장은 저상홈, 다른 쪽 승강장은 고상홈의 형태의 승강장을 만들어주실 수 있으신가요?

**Comment by kiwitreekor** [comment]
고려해 보도록 하겠습니다.

**Comment by kiwitreekor** [comment]
Closed via a1117ae.
